export const types = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTED : "REMOVE_SELECTED_PRODUCTED",
    ADD_TO_CART : "ADD_TO_CART"
}